dist: trusty
language: node_js
node_js:
- '8'
before_script:
  - npm install -g bower
  - bower install
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable